name: E2E Issue branch deletion

on:
  schedule:
    - cron: '30 23 * * *'  # Run at 23:30 UTC daily
  workflow_dispatch:  # Allow manual trigger

jobs:
  delete-issue-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to delete branches
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all branches
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete branches matching issue-<number> pattern
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get all branches
            const branches = await github.rest.repos.listBranches({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            });

            // Filter branches that match the pattern issue-<number>
            const issueBranches = branches.data.filter(branch => {
              return /^issue-\d+$/.test(branch.name);
            });

            console.log(`Found ${issueBranches.length} branches matching pattern issue-<number> out of ${branches.data.length} total branches retrieved`);

            // Delete each matching branch
            for (const branch of issueBranches) {
              try {
                console.log(`Deleting branch: ${branch.name}`);
                await github.rest.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `heads/${branch.name}`
                });
                console.log(`✅ Successfully deleted branch: ${branch.name}`);
              } catch (error) {
                console.error(`❌ Failed to delete branch ${branch.name}: ${error.message}`);
              }
            }

            console.log('WKND Trendsetters DA - Branch deletion process completed');
